<div class="page-content-wrapper">
    <div class="page-content">
    	<div class="row">
    		<div class="col-md-12">
    			<div class="portlet box grey">
    				<div class="portlet-title">
    					<div class="caption">{translate}tr_menu_tutorial{/translate}</div>
    				</div>
    				<div class="portlet-body tutorial">
						<h1>{translate}tutorial_general_title{/translate}</h1>
						<p>
							{translate}tutorial_general_text1{/translate}
						</p>
						<p>
							{translate}tutorial_general_text2{/translate}
						</p>
						<ul>
							<li>{translate}tutorial_general_li_title1{/translate}<br/>{translate}tutorial_general_li_text1{/translate}</li>
							<li>{translate}tutorial_general_li_title2{/translate}<br/>{translate}tutorial_general_li_text2{/translate}</li>
							<li>{translate}tutorial_general_li_title3{/translate}<br/>{translate}tutorial_general_li_text3{/translate}</li>
							<li>{translate}tutorial_general_li_title4{/translate}<br/>{translate}tutorial_general_li_text4{/translate}</li>
							<li>{translate}tutorial_general_li_title5{/translate}<br/>{translate}tutorial_general_li_text5{/translate}</li>
							<li>{translate}tutorial_general_li_title6{/translate}<br/>{translate}tutorial_general_li_text6{/translate}</li>
							<li>{translate}tutorial_general_li_title7{/translate}<br/>{translate}tutorial_general_li_text7{/translate}</li>
							<li>{translate}tutorial_general_li_title8{/translate}<br/>{translate}tutorial_general_li_text8{/translate}</li>
							<li>{translate}tutorial_general_li_title9{/translate}<br/>{translate}tutorial_general_li_text9{/translate}</li>
						</ul>
						<h2>{translate}tutorial_general_title1{/translate}</h2>
						<p>
							{translate}tutorial_general_text3{/translate}
						</p>
						<ul>
							<li>{translate}tutorial_general_li_title10{/translate}<br/>{translate}tutorial_general_li_text10{/translate}</li>
							<li>{translate}tutorial_general_li_title11{/translate}<br/>{translate}tutorial_general_li_text11{/translate}</li>
							<li>{translate}tutorial_general_li_title12{/translate}<br/>{translate}tutorial_general_li_text12{/translate}</li>
							<li>{translate}tutorial_general_li_title13{/translate}<br/>{translate}tutorial_general_li_text13{/translate}</li>
							<li>{translate}tutorial_general_li_title14{/translate}<br/>{translate}tutorial_general_li_text14{/translate}</li>
							<li>{translate}tutorial_general_li_title15{/translate}<br/>{translate}tutorial_general_li_text15{/translate}</li>
						</ul>
						<p>
							{translate}tutorial_general_text4{/translate}
						</p>
						<h2>{translate}tutorial_general_title2{/translate}</h2>
						<p>
							{translate}tutorial_general_text5{/translate}
						</p>
						<h3 id="dashboard">{translate}tutorial_dashboard_title{/translate}</h3>
						<p>
							{translate}tutorial_dashboard_text1{/translate}
						</p>
						<ul>
							<li>{translate}tutorial_dashboard_li_title1{/translate}<br/>{translate}tutorial_dashboard_li_text1{/translate}</li>
							<li>{translate}tutorial_dashboard_li_title2{/translate}<br/>{translate}tutorial_dashboard_li_text2{/translate}</li>
							<li>{translate}tutorial_dashboard_li_title3{/translate}<br/>{translate}tutorial_dashboard_li_text3{/translate}</li>
							<li>{translate}tutorial_dashboard_li_title4{/translate}<br/>{translate}tutorial_dashboard_li_text4{/translate}</li>
						</ul>
						<h3 id="fahrer">{translate}tutorial_driver_title{/translate}</h3>
						<p>
							{translate}tutorial_driver_text1{/translate}
						</p>
						<h4>{translate}tutorial_driver_title1{/translate}</h4>
						<p>
							{translate}tutorial_driver_text2{/translate}
						</p>
						<ul>
							<li>{translate}tutorial_driver_li_title1{/translate}<br/>{translate}tutorial_driver_li_text1{/translate}</li>
							<li>{translate}tutorial_driver_li_title2{/translate}</br>{translate}tutorial_driver_li_text2{/translate}</li>
						</ul>
						<p>
							{translate}tutorial_driver_text3{/translate}
						</p>
						<h4>{translate}tutorial_driver_title2{/translate}</h4>
						<p>
							{translate}tutorial_driver_text4{/translate}
						</p>
						<ul>
							<li>{translate}tutorial_driver_li_title3{/translate}<br/>{translate}tutorial_driver_li_text3{/translate}</li>
							<li>{translate}tutorial_driver_li_title4{/translate}<br/>{translate}tutorial_driver_li_text4{/translate}</li>
							<li>{translate}tutorial_driver_li_title5{/translate}<br/>{translate}tutorial_driver_li_text5{/translate}</li>
							<li>{translate}tutorial_driver_li_title6{/translate}<br/>{translate}tutorial_driver_li_text6{/translate}</li>
							<li>{translate}tutorial_driver_li_title7{/translate}<br/>{translate}tutorial_driver_li_text7{/translate}</li>
							<li>{translate}tutorial_driver_li_title8{/translate}<br/>{translate}tutorial_driver_li_text8{/translate}</li>
							<li>{translate}tutorial_driver_li_title9{/translate}<br/>{translate}tutorial_driver_li_text9{/translate}</li>
						</ul>
						<p>
							{translate}tutorial_driver_text5{/translate}
						</p>
						<h4>{translate}tutorial_driver_title3{/translate}</h4>
						<p>
							{translate}tutorial_driver_text6{/translate}
						</p>
						<ul>
							<li>{translate}tutorial_driver_li_title10{/translate}<br/>{translate}tutorial_driver_li_text10{/translate}</li>
							<li>{translate}tutorial_driver_li_title11{/translate}<br/>{translate}tutorial_driver_li_text10{/translate}</li>
						</ul>	
						<h3 id="mechaniker">{translate}tutorial_mechanics_title{/translate}</h3>
						<p>
							{translate}tutorial_mechanics_text1{/translate}
						</p>
						<h4>{translate}tutorial_mechanics_title1{/translate}</h4>
						<p>
							{translate}tutorial_mechanics_text2{/translate}
						</p>
						<ul>
							<li>{translate}tutorial_mechanics_li_title1{/translate}<br/>{translate}tutorial_mechanics_li_text1{/translate}</li>
							<li>{translate}tutorial_mechanics_li_title2{/translate}<br/>{translate}tutorial_mechanics_li_text2{/translate}</li>
							<li>{translate}tutorial_mechanics_li_title3{/translate}<br/>{translate}tutorial_mechanics_li_text3{/translate}</li>
							<li>{translate}tutorial_mechanics_li_title4{/translate}<br/>{translate}tutorial_mechanics_li_text4{/translate}</li>
						</ul>
						<p>
							{translate}tutorial_mechanics_text3{/translate}
						</p>
						<h4>{translate}tutorial_mechanics_title2{/translate}</h4>
						<p>
							{translate}tutorial_mechanics_text4{/translate}
						</p>
						<h3 id="wagen">{translate}tutorial_car_title{/translate}</h3>
						<p>
							{translate}tutorial_car_text1{/translate}
						</p>
						<h4>{translate}tutorial_car_title1{/translate}</h4>
						<p>
							{translate}tutorial_car_text2{/translate}
						</p>
						<p>
							{translate}tutorial_car_text3{/translate}
						</p>
						<h4>{translate}tutorial_car_title2{/translate}</h4>
						<p>
							{translate}tutorial_car_text4{/translate}
						</p>
						<ul>
							<li>{translate}tutorial_car_li_title1{/translate}<br/>{translate}tutorial_car_li_text1{/translate}</li>
							<li>{translate}tutorial_car_li_title2{/translate}<br/>{translate}tutorial_car_li_text2{/translate}</li>
							<li>{translate}tutorial_car_li_title3{/translate}<br/>{translate}tutorial_car_li_text3{/translate}</li>
							<li>{translate}tutorial_car_li_title4{/translate}<br/>{translate}tutorial_car_li_text4{/translate}</li>
						</ul>
						<p>
							{translate}tutorial_car_text5{/translate}
						</p>
						<h4>{translate}tutorial_car_title3{/translate}</h4>
						<p>
							{translate}tutorial_car_text6{/translate}
						</p>
						<ul>
							<li>{translate}tutorial_car_li_title5{/translate}<br/>{translate}tutorial_car_li_text5{/translate}</li>
							<li>{translate}tutorial_car_li_title6{/translate}<br/>{translate}tutorial_car_li_text6{/translate}</li>
						</ul>
						<p>
							{translate}tutorial_car_text7{/translate}
						</p>
						<h3 id="finanzen">{translate}tutorial_budget_title{/translate}</h3>
						<p>
							{translate}tutorial_budget_text1{/translate}
						</p>
						<h4>{translate}tutorial_budget_sub_title1{/translate}</h4>
						<p>
							{translate}tutorial_budget_sub_text1{/translate}
						</p>
						<ul>
							<li>{translate}tutorial_budget_sub_li_title1{/translate}<br/>{translate}tutorial_budget_sub_li_text1{/translate}</li>
							<li>{translate}tutorial_budget_sub_li_title2{/translate}<br/>{translate}tutorial_budget_sub_li_text2{/translate}</li>
							<li>{translate}tutorial_budget_sub_li_title3{/translate}<br/>{translate}tutorial_budget_sub_li_text3{/translate}</li>
						</ul>
						<p>
							{translate}tutorial_budget_sub_text2{/translate}
						</p>
						<h4>{translate}tutorial_budget_sub_title2{/translate}</h4>
						<p>
							{translate}tutorial_budget_sub_text3{/translate}
						</p>
						<h4>{translate}tutorial_budget_sub_title3{/translate}</h4>
						<p>
							{translate}tutorial_budget_sub_text4{/translate}
						</p>
						<br/><strong>{translate}tutorial_budget_sub_title4{/translate}</strong>
						<p>
							{translate}tutorial_budget_sub_text5{/translate}
						</p>
						<ul>
							<li>{translate}tutorial_budget_sub_li_title4{/translate}<br/>{translate}tutorial_budget_sub_li_text4{/translate}</li>
							<li>{translate}tutorial_budget_sub_li_title5{/translate}<br/>{translate}tutorial_budget_sub_li_text5{/translate}</li>
						</ul>
						<p>
							{translate}tutorial_budget_sub_text6{/translate}
						</p>
						<br/><strong>{translate}tutorial_budget_sub_title5{/translate}</strong>
						<p>
							{translate}tutorial_budget_sub_text7{/translate}
						</p>
						<ul>
							<li>{translate}tutorial_budget_sub_li_title6{/translate}<br/>{translate}tutorial_budget_sub_li_text6{/translate}</li>
							<li>{translate}tutorial_budget_sub_li_title7{/translate}<br/>{translate}tutorial_budget_sub_li_text7{/translate}</li>
							<li>{translate}tutorial_budget_sub_li_title8{/translate}<br/>{translate}tutorial_budget_sub_li_text8{/translate}</li>
						</ul>
						<br/><strong>{translate}tutorial_budget_sub_title6{/translate}</strong>
						<p>
							{translate}tutorial_budget_sub_text8{/translate}
						</p>
						<ul>
							<li>{translate}tutorial_budget_sub_li_title9{/translate}<br/>{translate}tutorial_budget_sub_li_text9{/translate}</li>
							<li>{translate}tutorial_budget_sub_li_title10{/translate}<br/>{translate}tutorial_budget_sub_li_text10{/translate}</li>
						</ul>
						<h3 id="rennen">{translate}tutorial_race_title{/translate}</h3>
						<p>
							{translate}tutorial_race_text1{/translate}
						</p>
						<p>
							{translate}tutorial_race_text2{/translate}
						</p>
						<p>
							{translate}tutorial_race_text3{/translate}
						</p>
						<ul>
							<li>{translate}tutorial_race_li_header1{/translate}<br/>{translate}tutorial_race_li_text1{/translate}</li>
							<li>{translate}tutorial_race_li_header2{/translate}<br/>{translate}tutorial_race_li_text2{/translate}</li>
							<li>{translate}tutorial_race_li_header3{/translate}<br/>{translate}tutorial_race_li_text3{/translate}</li>
							<li>{translate}tutorial_race_li_header4{/translate}<br/>{translate}tutorial_race_li_text4{/translate}</li>
							<li>{translate}tutorial_race_li_header5{/translate}<br/>{translate}tutorial_race_li_text5{/translate}</li>
							<li>{translate}tutorial_race_li_header6{/translate}<br/>{translate}tutorial_race_li_text6{/translate}</li>
							<li>{translate}tutorial_race_li_header7{/translate}<br/>{translate}tutorial_race_li_text7{/translate}</li>
							<li>{translate}tutorial_race_li_header8{/translate}<br/>{translate}tutorial_race_li_text8{/translate}</li>
							<li>{translate}tutorial_race_li_header9{/translate}<br/>{translate}tutorial_race_li_text9{/translate}</li>
						</ul>
						<h4>{translate}tutorial_race_training_title{/translate}</h4>
						<p>
							{translate}tutorial_race_training_text1{/translate}
						</p>
						<p>
							{translate}tutorial_race_training_text2{/translate}
						</p>
						<p>
							{translate}tutorial_race_training_text3{/translate}
						</p>
						<br/><strong>{translate}tutorial_race_comment_title{/translate}</strong>
						<p>
							{translate}tutorial_race_comment_text1{/translate}
						</p>
						<p>
							{translate}tutorial_race_comment_text2{/translate}
						</p>
						<ul>
							<li>{translate}tutorial_race_comment_li_header1{/translate}<br/>{translate}tutorial_race_comment_li_text1{/translate}</li>
							<li>{translate}tutorial_race_comment_li_header2{/translate}<br/>{translate}tutorial_race_comment_li_text2{/translate}</li>
							<li>{translate}tutorial_race_comment_li_header3{/translate}<br/>{translate}tutorial_race_comment_li_text3{/translate}</li>
							<li>{translate}tutorial_race_comment_li_header4{/translate}<br/>{translate}tutorial_race_comment_li_text4{/translate}</li>
							<li>{translate}tutorial_race_comment_li_header5{/translate}<br/>{translate}tutorial_race_comment_li_text5{/translate}</li>
							<li>{translate}tutorial_race_comment_li_header6{/translate}</li>
						</ul>
						<p>
							{translate}tutorial_race_comment_text3{/translate}
						</p>
						<h4>{translate}tutorial_race_qualification_title{/translate}</h4>
						<p>
							{translate}tutorial_race_qualification_text1{/translate}
						</p>
						<p>
							{translate}tutorial_race_qualification_text2{/translate}
						</p>
						<h4>{translate}tutorial_race_race_title{/translate}</h4>
						<p>
							{translate}tutorial_race_race_text1{/translate}
						</p>
						<p>
							{translate}tutorial_race_race_text2{/translate}
						</p>
						<ul>
							<li>{translate}tutorial_race_race_li_text1{/translate}</li>
							<li>{translate}tutorial_race_race_li_text2{/translate}</li>
							<li>{translate}tutorial_race_race_li_text3{/translate}</li>
						</ul>
						<p>
							{translate}tutorial_race_race_text3{/translate}
						</p>
						<p>
							{translate}tutorial_race_race_text4{/translate}
						</p>
						<p>
							{translate}tutorial_race_race_text5{/translate}
						</p>
						<h3 id="statistik">{translate}tutorial_statistics_title{/translate}</h3>
						<p>
							{translate}tutorial_statistics_text1{/translate}
						</p>
						<h4>{translate}tutorial_statistics_sub_header1{/translate}</h4>
						<p>
							{translate}tutorial_statistics_sub_text1{/translate}
						</p>
						<h4>{translate}tutorial_statistics_sub_header2{/translate}</h4>
						<p>
							{translate}tutorial_statistics_sub_text2{/translate}
						</p>
						<h4>{translate}tutorial_statistics_sub_header3{/translate}</h4>
						<p>
							{translate}tutorial_statistics_sub_text3{/translate}
						</p>
						<h4>{translate}tutorial_statistics_sub_header4{/translate}</h4>
						</p>
							{translate}tutorial_statistics_sub_text4{/translate}
						</p>
						<h4>{translate}tutorial_statistics_sub_header5{/translate}</h4>
						<p>
							{translate}tutorial_statistics_sub_text5{/translate}
						</p>
						<h4>{translate}tutorial_statistics_sub_header6{/translate}</h4>
						<p>
							{translate}tutorial_statistics_sub_text6{/translate}
						</p>
						<h3 id="profil">{translate}tutorial_profile_title{/translate}</h3>
						<p>
							{translate}tutorial_profile_text1{/translate}
						</p>
						<ul>
							<li>{translate}tutorial_profile_li_header1{/translate}<br/>{translate}tutorial_profile_li_text1{/translate}</li>
							<li>{translate}tutorial_profile_li_header2{/translate}<br/>{translate}tutorial_profile_li_text2{/translate}</li>
							<li>{translate}tutorial_profile_li_header3{/translate}<br/>{translate}tutorial_profile_li_text3{/translate}</li>
							<li>{translate}tutorial_profile_li_header4{/translate}<br/>{translate}tutorial_profile_li_text4{/translate}</li>
							<li>{translate}tutorial_profile_li_header5{/translate}<br/>{translate}tutorial_profile_li_text5{/translate}</li>
						</ul>
						<p>
							{translate}tutorial_profile_text2{/translate}
						</p>
					</div>
			    </div>
			</div>
		</div>
	</div>
</div>
